### ISSUE TITLE
Feature Request - Include full list of constants

### ISSUE THREAD

**Issue by iembry** [r-quantities/constants#5]
The article that you referenced also refers the reader to the [NIST Fundamental Constants](https://physics.nist.gov/cuu/Constants/index.html)] that includes a link to the [Fundamental Physical Constants --- Complete Listing](https://physics.nist.gov/cuu/Constants/Table/allascii.txt).

When will you include all of the available constants for the complete listing?

For example, you don't have the acceleration due to gravity (g) yet in the constants package.

Thank you.

Irucka

**Comment by Enchufa2** [comment]
This package strictly follows the CODATA internationally recommended values, as NIST does in principle. The standard acceleration of gravity is not part of the CODATA published values, so I'm not sure why NIST includes it. Note that it's not a fundamental physical constant. It's just a value adopted in 1901. In fact, `g` varies across the Earth's surface between 9.76 and 9.83 approximately. Therefore, I don't see any advantage in including it here.

What do you think, @edzer?

**Comment by edzer** [comment]
I agree.

**Comment by Enchufa2** [comment]
@iembry So we will stick to CODATA values.

If you need a precise calculation, you need to estimate `g` yourself, and this package includes the Newtonian constant of gravitation `G` with its error for that matter. If not, 9.8 is just as good as the adopted standard value, which is 9.80665.
