### ISSUE TITLE
"syms_with_errors" and "syms_with_quantities" is empty.

### ISSUE THREAD

**Issue by piiskop** [r-quantities/constants#8]
```
librarian::shelf(c(
  "constants"
))
View(syms_with_errors)
```

> Pairlist of length 0

**Comment by Enchufa2** [comment]
Do you have the errors and quantities packages installed? If not, install them, restart your session and try again.

**Comment by piiskop** [comment]
I did not have them installed and had no idea I needed separate packages for these provided functions. This is a very strange behavior to me. The session restart was only necessary for `syms_with_quantities`.

**Comment by Enchufa2** [comment]
From the manual page, see `?syms`:

> The enriched versions of ‘syms’ are available only if the
     corresponding optional packages, ‘errors’, ‘units’ and/or
     ‘quantities’ are installed. See the documentation of these
     packages for further information.
